apiVersion: v1
kind: Service
metadata:
  name: nats-port-forward-service
spec:
  selector:
    app: nats
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
      nodePort: 30001
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
      nodePort: 30002