apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  type: ClusterIP
  ports:
    - name: products
      protocol: TCP
      port: 3000
      targetPort: 3000
